<div id="pnl_edititemsgrid">
	<div class="fgta-page-title">Daftar Items</div>
	<div id="pnl_edititemsgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edititemsgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edititemsgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edititemsgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edititemsgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/merchorderin-itemsgrid-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
<th type="check">chk</th>					
					<th mapping="merchitem_name">merchitem_name</th>
					<th mapping="merchitem_art">merchitem_art</th>
					<th mapping="merchitem_mat">merchitem_mat</th>
					<th mapping="merchitem_col">merchitem_col</th>
					<th mapping="merchitem_size">merchitem_size</th>
					<th mapping="merchitem_name">merchitem_name</th>
					<th mapping="merchorderinitem_price" style="text-align: right" formatter="row_format_number">merchorderinitem_price</th>
					<th mapping="merchorderinitem_pricediscpercent" style="text-align: right" formatter="row_format_number">merchorderinitem_pricediscpercent</th>
					<th mapping="merchorderinitem_isdiscvalue" type="checkbox">merchorderinitem_isdiscvalue</th>
					<th mapping="merchquotoutitem_isdiscvalue" type="checkbox">merchquotoutitem_isdiscvalue</th>
					<th mapping="merchitem_saldodt">merchitem_saldodt</th>
					<th mapping="merchitem_lastrv">merchitem_lastrv</th>
					<th mapping="merchitem_lastrvdt">merchitem_lastrvdt</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ART</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">MAT</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">COL</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SIZE</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Price</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Disc (%)</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disc by Value</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disc by Value</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tanggal Saldo</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Last RV</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Last RV Date</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



	<div class="pnl_edititemsgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edititemsgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edititemsgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
