<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Syn TBInv</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_tbinvsum_id" class="easyui-textbox" mapping="tbinvsum_id"  maxlength="16" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">BLOCK</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_block" class="easyui-textbox" mapping="block"  maxlength="5" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">dt</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_dt" class="easyui-datebox" style="width: 400px" mapping="dt" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">region_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_region_id" class="easyui-textbox" mapping="region_id"  maxlength="5" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">branch_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_branch_id" class="easyui-textbox" mapping="branch_id"  maxlength="7" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_id" class="easyui-textbox" mapping="heinv_id"  maxlength="13" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_art</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_art" class="easyui-textbox" mapping="heinv_art"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_mat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_mat" class="easyui-textbox" mapping="heinv_mat"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_col</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_col" class="easyui-textbox" mapping="heinv_col"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_heinv_iskonsinyasi" class="easyui-checkbox c1" mapping="heinv_iskonsinyasi" data-options="label: 'heinv_iskonsinyasi', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_priceori</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_priceori" class="easyui-numberbox" mapping="heinv_priceori" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_priceadj</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_priceadj" class="easyui-numberbox" mapping="heinv_priceadj" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_pricegross</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_pricegross" class="easyui-numberbox" mapping="heinv_pricegross" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_price</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_price" class="easyui-numberbox" mapping="heinv_price" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_pricedisc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_pricedisc" class="easyui-numberbox" mapping="heinv_pricedisc" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_pricenett</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_pricenett" class="easyui-numberbox" mapping="heinv_pricenett" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">gtype</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_gtype" class="easyui-textbox" mapping="gtype"  maxlength="1" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">season_group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_season_group" class="easyui-textbox" mapping="season_group"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">season_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_season_id" class="easyui-textbox" mapping="season_id"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">season_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_rvid" class="easyui-textbox" mapping="rvid"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">rvdt</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_rvdt" class="easyui-datebox" style="width: 400px" mapping="rvdt" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">rvqty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_rvqty" class="easyui-numberbox" mapping="rvqty" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">age</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_age" class="easyui-numberbox" mapping="age" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvctg_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvctg_id" class="easyui-textbox" mapping="heinvctg_id"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvctg_name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvctg_name" class="easyui-textbox" mapping="heinvctg_name"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvctg_class</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvctg_class" class="easyui-textbox" mapping="heinvctg_class"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvctg_gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvctg_gender" class="easyui-textbox" mapping="heinvctg_gender"  maxlength="1" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvctg_sizetag</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvctg_sizetag" class="easyui-textbox" mapping="heinvctg_sizetag"  maxlength="5" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinvgro_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinvgro_id" class="easyui-textbox" mapping="heinvgro_id"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_group1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_group1" class="easyui-textbox" mapping="heinv_group1"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_group2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_group2" class="easyui-textbox" mapping="heinv_group2"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_gender" class="easyui-textbox" mapping="heinv_gender"  maxlength="1" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_color1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_color1" class="easyui-textbox" mapping="heinv_color1"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_color2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_color2" class="easyui-textbox" mapping="heinv_color2"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_color3</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_color3" class="easyui-textbox" mapping="heinv_color3"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_hscode_ship</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_hscode_ship" class="easyui-textbox" mapping="heinv_hscode_ship"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_hscode_ina</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_hscode_ina" class="easyui-textbox" mapping="heinv_hscode_ina"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_plbname</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_plbname" class="easyui-textbox" mapping="heinv_plbname"  maxlength="100" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ref_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_ref_id" class="easyui-textbox" mapping="ref_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">invcls_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_invcls_id" class="easyui-textbox" mapping="invcls_id"  maxlength="8" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_heinv_isweb" class="easyui-checkbox c1" mapping="heinv_isweb" data-options="label: 'heinv_isweb', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_weight</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_weight" class="easyui-numberbox" mapping="heinv_weight" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_length</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_length" class="easyui-numberbox" mapping="heinv_length" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_width</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_width" class="easyui-numberbox" mapping="heinv_width" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_height</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_height" class="easyui-numberbox" mapping="heinv_height" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_webdescr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_webdescr" class="easyui-textbox" mapping="heinv_webdescr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_other1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_other1" class="easyui-textbox" mapping="heinv_other1"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_other2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_other2" class="easyui-textbox" mapping="heinv_other2"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_other3</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_other3" class="easyui-textbox" mapping="heinv_other3"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_other4</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_other4" class="easyui-textbox" mapping="heinv_other4"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_other5</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_other5" class="easyui-textbox" mapping="heinv_other5"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_produk</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_produk" class="easyui-textbox" mapping="heinv_produk"  maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_bahan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_bahan" class="easyui-textbox" mapping="heinv_bahan"  maxlength="70" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_pemeliharaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_pemeliharaan" class="easyui-textbox" mapping="heinv_pemeliharaan"  maxlength="100" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_logo</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_logo" class="easyui-textbox" mapping="heinv_logo"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_dibuatdi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_dibuatdi" class="easyui-textbox" mapping="heinv_dibuatdi"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">heinv_modifydate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_heinv_modifydate" class="easyui-textbox" mapping="heinv_modifydate"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">lastcost</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_lastcost" class="easyui-numberbox" mapping="lastcost" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">lastcostid</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_lastcostid" class="easyui-textbox" mapping="lastcostid"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">lastcostdt</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_lastcostdt" class="easyui-datebox" style="width: 400px" mapping="lastcostdt" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">lastpriceid</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_lastpriceid" class="easyui-textbox" mapping="lastpriceid"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">lastpricedt</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_lastpricedt" class="easyui-datebox" style="width: 400px" mapping="lastpricedt" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">beg</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_beg" class="easyui-numberbox" mapping="beg" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">rv</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_rv" class="easyui-numberbox" mapping="rv" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">tin</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_tin" class="easyui-numberbox" mapping="tin" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">tout</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_tout" class="easyui-numberbox" mapping="tout" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">sl</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_sl" class="easyui-numberbox" mapping="sl" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">do</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_do" class="easyui-numberbox" mapping="do" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">aj</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_aj" class="easyui-numberbox" mapping="aj" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">end</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_end" class="easyui-numberbox" mapping="end" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">tts</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_tts" class="easyui-numberbox" mapping="tts" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C01</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C01" class="easyui-numberbox" mapping="C01" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C02</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C02" class="easyui-numberbox" mapping="C02" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C03</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C03" class="easyui-numberbox" mapping="C03" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C04</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C04" class="easyui-numberbox" mapping="C04" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C05</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C05" class="easyui-numberbox" mapping="C05" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C06</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C06" class="easyui-numberbox" mapping="C06" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C07</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C07" class="easyui-numberbox" mapping="C07" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C08</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C08" class="easyui-numberbox" mapping="C08" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C09</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C09" class="easyui-numberbox" mapping="C09" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C10</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C10" class="easyui-numberbox" mapping="C10" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C11</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C11" class="easyui-numberbox" mapping="C11" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C12</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C12" class="easyui-numberbox" mapping="C12" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C13</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C13" class="easyui-numberbox" mapping="C13" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C14</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C14" class="easyui-numberbox" mapping="C14" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C15</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C15" class="easyui-numberbox" mapping="C15" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C16</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C16" class="easyui-numberbox" mapping="C16" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C17</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C17" class="easyui-numberbox" mapping="C17" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C18</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C18" class="easyui-numberbox" mapping="C18" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C19</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C19" class="easyui-numberbox" mapping="C19" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C20</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C20" class="easyui-numberbox" mapping="C20" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C21</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C21" class="easyui-numberbox" mapping="C21" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C22</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C22" class="easyui-numberbox" mapping="C22" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C23</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C23" class="easyui-numberbox" mapping="C23" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C24</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C24" class="easyui-numberbox" mapping="C24" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">C25</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_C25" class="easyui-numberbox" mapping="C25" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/invsum-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

