<div class="contenttitle">My Profile </div>

<div>
	<div>
		<img src="" style="width: 400px; height: 250px;">
	</div>

	<div>
		<div><a href="index.php/module/retail/webcommerce/falloexplore"href="">Allo Explore</a></div>
		<div><a href="index.php/module/retail/webcommerce/fprofile/preference"href="">My Preference</a></div>
		<div><a href="index.php/module/retail/webcommerce/fprofile/coupons"href="">My Coupons</a></div>
		<div><a href="index.php/module/retail/webcommerce/fprofile/wishlist"href="">Wishlist</a></div>
		<div><a href="index.php/module/retail/webcommerce/ftrxhistory">Transaction History</a></div>
	</div>



</div>
