<div class="contenttitle">My Preference</div>

<div>


	<div class="formrow">
		<div class="formrow-label">Name</div>
		<div><input type="text"></div>
	</div>

	<div class="formrow">
		<span>
			<input type="radio" id="male" name="gender" value="male">
			<label for="male">Male</label>
		</span>
		
		<span>
			<input type="radio" id="female" name="gender" value="female">
			<label for="female">Female</label>
		</span>	
	</div>


	<div class="formrow">
		<div class="formrow-label">Email Address</div>
		<div><input type="text"></div>
	</div>	

	<div class="formrow">
		<div class="formrow-label">Primary Phone Number</div>
		<div><input type="text" disabled></div>
		<div class="formrow-info">This number is not changebale and used for login purpose</div>
	</div>


	<div class="formrow">
		<div class="formrow-label">Other Phone Numbers</div>
		<ul>
			<li>0818xxxxx9000  [remove]</li>
		</ul>		
	</div>

	<div class="formrow">
		<div>Add Other phone number (require OTP)</div>
		<div>
			<input type="text">
			<button id="btn_phoneadd" class="fbutton fbutton-side fbutton-black" style="height: 30px">Add</button>
		</div>
	</div>

	<div class="formrow" style="margin-top:30px">
		<button id="btn_preference" class="fbutton fbutton-black">Submit</button>
	</div>
</div>



<div>
	Back to <a href="index.php/module/retail/webcommerce/fprofile/myprofileview">My Profile</a>
</div>