<div class="ost-container">
	<div class="ost-blok-2-left">
		<div class="ost-text-title">OUR STORES</div>
		<div class="ost-text-content">Furla Group has highly-operative and fully structured regional headquarters in New York, Hong Kong Saar and Tokyo. Its mono-brand network branches out across 100 countries with 444 stores worldwide, which offer a special customer experience in a refined setting.</div>
	</div>

	<div class="ost-blok-2-right">
		<div class="ost-blok-image"></div>
	</div>
</div>


<div class="ost-container">
	<div class="ost-blok-maps"></div>
</div>

<div class="ost-container">

	<div class="ost-blok-3">
		JAKARTA
	</div>	

</div>
