<div class="contenttitle"><?=$this->siteinfo->name?></div>



<div class="sl-container">
	<div>
		<img src="" style="width: 600px; height: 400px;">
	</div>

	<div class="sl-address">
		<div class="sl-address-content">
			<div>Address</div>
			<div><?=$this->siteinfo->site_address1?></div>
			<div><?=$this->siteinfo->site_address2?></div>
			<div><?=$this->siteinfo->site_address3?></div>
			<div><?=$this->siteinfo->site_phone?></div>
			<div><?=$this->siteinfo->site_contact?></div>

		</div>

		<div class="sl-address-content">

		</div>
	</div>
</div>

<div>
	<div>Address</div>
	<div><?=$this->siteinfo->site_address1?></div>
	<div><?=$this->siteinfo->site_address2?></div>
	<div><?=$this->siteinfo->site_address3?></div>
	<div><?=$this->siteinfo->site_phone?></div>
	<div><?=$this->siteinfo->site_contact?></div>

	<div>View in <a href="http://www.google.com/maps/place/<?=$this->siteinfo->site_geoloc?>" target="newtab">maps</a></div>



</div>

<br><br>
<div>
	<a href="index.php/module/retail/webcommerce/fstorelocator">All Stores</a>
</div>
