<div class="contenttitle">Contanct Us</div>

<div>
	<div class="formrow">
		<div class="formrow-label">Name</div>
		<div><input type="text"></div>
	</div>
	<div class="formrow">
		<div class="formrow-label">Email Address</div>
		<div><input type="text"></div>
	</div>

	<div class="formrow">
		<div class="formrow-label">Phone Number</div>
		<div><input type="text"></div>
	</div>

	<div class="formrow">
		<div class="formrow-label">Message</div>
		<div><input type="text"></div>
	</div>

	<div class="formrow">
		<button class="fbutton fbutton-black">Submit</button>
	</div>
</div>


<!--
https://code.tutsplus.com/tutorials/build-your-own-captcha-and-contact-form-in-php--net-5362
-->