<div class="contenttitle">Content Disclaimer</div>

<div>
Please read this disclaimer carefully before using our page.
(BRAND) logo, product & campaign images and content displayed on the website is the intellectual property of (BRAND).
Trans Fashion Indonesia logo and editorial content displayed on this website is the intellectual property of Trans Fashion Indonesia
Instagram and Facebook logo displayed on this website is the intellectual property of Facebook
Google logo displayed on this website is the intellectual property of Google
You may not reuse, republish or reprint such content without our written permission. While the information on this website has been verified to the best of our abilities, we cannot guarantee that there are no mistakes or errors. 
We reserve the right to change this policy at any given time of which you will be promptly updated. If you want to make sure that you are up to date with the latest changes, we advise you to frequently visit this page.
If you have any questions about this Disclaimer, please contact us.

Contact
cs@transfashionindonesia.com

</div>

