
<div class="contenttitle">Exchange Policy</div>

<div>

Merchandise eligible for exchange are full priced items only (discount or promo items not eligible), within 14 days of purchase, with original receipt, all hang tags & labels fully intact and absolutely not used.
Only merchandise purchased under PT TransFashion Indonesia stores are eligible for exchange with the following terms & conditions:
If the alternative item to exchange is of lower value, there will be no refund for difference.
If the alternative item to exchange is of higher value, customers  have to top up the difference in amount.
No returns or exchange for perfumes, jewelry, sunglasses, socks and body wear
All sale / discounted merchandise cannot be exchanged or returned. 
All purchases are final with no refunds and no returns.


</div>
