<div class="contenttitle">Warranty, Repair & Service Policy</div>

<div>

Product warranty / repair is only valid for products (Furla Bags) purchased in our stores under PT Trans Fashion Indonesia.
Full price items will receive a warranty of 6 months after purchase with original receipt/ original e-receipt with following terms & conditions:
a. Repair & spare part service is available for a price.
b. Leather damage is not included in the warranty.
c, Product cleaning is not included in the warranty.
PT Trans Fashion Indonesia holds the final right of product assessment result.
Customers would need to fill in Form of “Product Repair Service Request”, with terms & conditions. This service is not free of charge and prices may vary as per the service requirement or spare parts replacement.
A down payment of Rp. 100,000 is mandatory to process the Repair Service.
Repair requests may take a minimum of 1 month to process, this is also conditioned with the kind of repair or if a spare part needs to be replaced and its availability.
Only official & genuine spare parts from Brand are to be used during repair services.
Customers must present / submit the  original Form of “Product Repair Service Request”  to collect their product from the store.
All finished / completed repairs must be picked up by the customer within 1 month after receiving confirmation from our staff. PT Trans Fashion Indonesia cannot accept any responsibility for the safety of the product after the above mentioned pick up period is over. 
PT Trans Fashion Indonesia is absolutely exempted from any responsibility of above mentioned merchandise' safe keep, in case of natural disasters. flooding, burglary or any situation out of company’s control.

</div>
