<div id="pnl_list">
	<div class="fgta-page-title">Daftar Merchandise Groups</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>

		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-param" style="width: 280px">
				<div class="list-search-item" style="width: 50px; align-self:center;">Cari</div>
				<div class="list-search-item" style="width: 200px">
					<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
				</div>
			</div>

			<div class="list-search-param" style="width: 280px">
				<div class="list-search-item" style="width: 50px; align-self:center; text-align: right">Cluster</div>
				<div class="list-search-item" style="width: 200px">
					<input id="pnl_list-txt_search_cluster" class="easyui-combo" style="width: 100%" data-options="editable:false">
				</div>
			</div>

			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>

		</div>
		
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="merchitemgro_id">merchitemgro_id</th>
					<th mapping="merchitemgro_name">merchitemgro_name</th>
					<th mapping="merchitemgro_descr">merchitemgro_descr</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Category Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Description</td>

				</tr>
			</thead>
		</table>
	</div>



</div>