<?php require_once dirname(__FILE__).'/webmerchitemcat-list.phtml' ?>
<?php require_once dirname(__FILE__).'/webmerchitemcat-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/webmerchitemcat-picturegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/webmerchitemcat-pictureform.phtml' ?>
<?php require_once dirname(__FILE__).'/webmerchitemcat-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/webmerchitemcat-propform.phtml' ?>



