<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Merchandise Raw</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_id" class="easyui-textbox" mapping="merchraw_id"  maxlength="14" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Merch Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_name" class="easyui-textbox" mapping="merchraw_name"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_gender" class="easyui-textbox" mapping="merchraw_gender"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Category Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_catcode" class="easyui-textbox" mapping="merchraw_catcode"  maxlength="15" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Category Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_catname" class="easyui-textbox" mapping="merchraw_catname"  maxlength="100" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Line</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_line" class="easyui-textbox" mapping="merchraw_line"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Style</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_style" class="easyui-textbox" mapping="merchraw_style"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Style Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_stylename" class="easyui-textbox" mapping="merchraw_stylename"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tipology Macro</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_tipologymacro" class="easyui-textbox" mapping="merchraw_tipologymacro"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tipology</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_tipology" class="easyui-textbox" mapping="merchraw_tipology"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Weight Gross</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_weightgross" class="easyui-numberbox" mapping="merchraw_weightgross" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Weight Nett</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_weightnett" class="easyui-numberbox" mapping="merchraw_weightnett" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SKU</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_sku" class="easyui-textbox" mapping="merchraw_sku"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SKU Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_skutype" class="easyui-textbox" mapping="merchraw_skutype"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Serial 1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_serial1" class="easyui-textbox" mapping="merchraw_serial1"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Serial 2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_serial2" class="easyui-textbox" mapping="merchraw_serial2"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Color Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_colcode" class="easyui-textbox" mapping="merchraw_colcode"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Color Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_colname" class="easyui-textbox" mapping="merchraw_colname"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Short Color Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_colnameshort" class="easyui-textbox" mapping="merchraw_colnameshort"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Material Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_matcode" class="easyui-textbox" mapping="merchraw_matcode"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Material Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_matname" class="easyui-textbox" mapping="merchraw_matname"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Short Material Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_matnameshort" class="easyui-textbox" mapping="merchraw_matnameshort"  maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Material Composition</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_matcmpst" class="easyui-textbox" mapping="merchraw_matcmpst"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Lining Composition</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_liningcmpst" class="easyui-textbox" mapping="merchraw_liningcmpst"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sole Composition 1</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_solcmpst1" class="easyui-textbox" mapping="merchraw_solcmpst1"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sole Composition 2</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_solcmpst2" class="easyui-textbox" mapping="merchraw_solcmpst2"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Made In</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_madein" class="easyui-textbox" mapping="merchraw_madein"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Width Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_widthgroup" class="easyui-textbox" mapping="merchraw_widthgroup"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Size</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_size" class="easyui-textbox" mapping="merchraw_size"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dimension</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_dim" class="easyui-textbox" mapping="merchraw_dim"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dimension Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_dimgroup" class="easyui-textbox" mapping="merchraw_dimgroup"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Length</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_dimlength" class="easyui-numberbox" mapping="merchraw_dimlength" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Width</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_dimwidth" class="easyui-numberbox" mapping="merchraw_dimwidth" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Height</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_dimheight" class="easyui-numberbox" mapping="merchraw_dimheight" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Barcode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_merchraw_barcode" class="easyui-textbox" mapping="merchraw_barcode"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Brand</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_brand_id" class="easyui-combo" style="width: 400px" mapping="brand_id" display="brand_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Cluster harus diisi'"   validType="requiredcombo['pnl_edit-cbo_brand_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		
		
		
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

