<div id="pnl_list">
	<div class="fgta-page-title">Daftar Merchandise Raw</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="merchraw_id">merchraw_id</th>
					<th mapping="merchraw_name">merchraw_name</th>
					<th mapping="merchraw_gender">merchraw_gender</th>
					<th mapping="merchraw_catcode">merchraw_catcode</th>
					<th mapping="merchraw_catname">merchraw_catname</th>
					<th mapping="merchraw_line">merchraw_line</th>
					<th mapping="merchraw_style">merchraw_style</th>
					<th mapping="merchraw_stylename">merchraw_stylename</th>
					<th mapping="merchraw_tipologymacro">merchraw_tipologymacro</th>
					<th mapping="merchraw_tipology">merchraw_tipology</th>
					<th mapping="merchraw_weightgross" style="text-align: right"  formatter="row_format_number">merchraw_weightgross</th>
					<th mapping="merchraw_weightnett" style="text-align: right"  formatter="row_format_number">merchraw_weightnett</th>
					<th mapping="merchraw_sku">merchraw_sku</th>
					<th mapping="merchraw_skutype">merchraw_skutype</th>
					<th mapping="merchraw_serial1">merchraw_serial1</th>
					<th mapping="merchraw_serial2">merchraw_serial2</th>
					<th mapping="merchraw_colcode">merchraw_colcode</th>
					<th mapping="merchraw_colname">merchraw_colname</th>
					<th mapping="merchraw_colnameshort">merchraw_colnameshort</th>
					<th mapping="merchraw_matcode">merchraw_matcode</th>
					<th mapping="merchraw_matname">merchraw_matname</th>
					<th mapping="merchraw_matnameshort">merchraw_matnameshort</th>
					<th mapping="merchraw_matcmpst">merchraw_matcmpst</th>
					<th mapping="merchraw_liningcmpst">merchraw_liningcmpst</th>
					<th mapping="merchraw_solcmpst1">merchraw_solcmpst1</th>
					<th mapping="merchraw_solcmpst2">merchraw_solcmpst2</th>
					<th mapping="merchraw_madein">merchraw_madein</th>
					<th mapping="merchraw_widthgroup">merchraw_widthgroup</th>
					<th mapping="merchraw_size">merchraw_size</th>
					<th mapping="merchraw_dim">merchraw_dim</th>
					<th mapping="merchraw_dimgroup">merchraw_dimgroup</th>
					<th mapping="merchraw_dimlength" style="text-align: right"  formatter="row_format_number">merchraw_dimlength</th>
					<th mapping="merchraw_dimwidth" style="text-align: right"  formatter="row_format_number">merchraw_dimwidth</th>
					<th mapping="merchraw_dimheight" style="text-align: right"  formatter="row_format_number">merchraw_dimheight</th>
					<th mapping="merchraw_barcode">merchraw_barcode</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Merch Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Gender</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Category Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Category Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Line</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Style</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Style Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tipology Macro</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tipology</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Weight Gross</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Weight Nett</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SKU</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SKU Type</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Serial 1</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Serial 2</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Color Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Color Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Short Color Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Material Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Material Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Short Material Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Material Composition</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Lining Composition</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Sole Composition 1</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Sole Composition 2</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Made In</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Width Group</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Size</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dimension</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dimension Group</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Length</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Width</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Height</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Barcode</td>

				</tr>
			</thead>
		</table>
	</div>



</div>